package org.nir.bookstore.entities;
// Generated 3 Dec 2020, 21:03:10 by Hibernate Tools 5.2.12.Final

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {

	private Integer orderId;
	private Integer bookId;
	/*
	 *REFACTORING:REMOVE: private int quantity; private float subtotal;
	 */

	public OrderDetailId() {
	}

	
	public OrderDetailId(Integer orderId, Integer bookId) {
		this.orderId = orderId;
		this.bookId = bookId;
		/*
		 * this.quantity = quantity; this.subtotal = subtotal;
		 */
	}

	@Column(name = "order_id")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "book_id")
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@Override
	public int hashCode()
	{
		return Objects.hash(bookId, orderId);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderDetailId other = (OrderDetailId) obj;
		return Objects.equals(bookId, other.bookId) && Objects.equals(orderId, other.orderId);
	}

	/*
	 * @Column(name = "quantity", nullable = false) public int getQuantity() {
	 * return this.quantity; }
	 * 
	 * public void setQuantity(int quantity) { this.quantity = quantity; }
	 * 
	 * @Column(name = "subtotal", nullable = false, precision = 12, scale = 0)
	 * public float getSubtotal() { return this.subtotal; }
	 * 
	 * public void setSubtotal(float subtotal) { this.subtotal = subtotal; }
	 */

	
}
