package org.nir.bookstore.entities;
// Generated 3 Dec 2020, 21:03:10 by Hibernate Tools 5.2.12.Final

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable
{
	
	private Book book;
	private BookOrder bookOrder;
	
	public OrderDetailId() {}
	
	//Refactoirng : add the nullable = false
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "book_id", insertable = false, updatable = false,nullable = false )
		public Book getBook()
		{
			return this.book;
		}

		public void setBook(Book book)
		{
			this.book = book;
		}

		//Refactoring: add the nullable = false
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "order_id", insertable = false, updatable = false , nullable = false)
		public BookOrder getBookOrder()
		{
			return this.bookOrder;
		}

		public void setBookOrder(BookOrder bookOrder)
		{
			this.bookOrder = bookOrder;
		}

		@Override
		public int hashCode()
		{
			final int prime = 31;
			int result = 1;
			result = prime * result + ((book == null) ? 0 : book.hashCode());
			result = prime * result + ((bookOrder == null) ? 0 : bookOrder.hashCode());
			return result;
		}

		@Override
		public boolean equals(Object obj)
		{
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			OrderDetailId other = (OrderDetailId) obj;
			if (book == null) {
				if (other.book != null)
					return false;
			} else if (!book.equals(other.book))
				return false;
			if (bookOrder == null) {
				if (other.bookOrder != null)
					return false;
			} else if (!bookOrder.equals(other.bookOrder))
				return false;
			return true;
		}

		

		
		
	
		
	//REFACTORING : REMOVE ALL PREVIOUS getter/setters and equals , hashCode methods
	///The getQuanitity() and getSubTotal moved to OrderDetail with the annotations!!!
	
	

	

	
}
